version: 2.1

orbs:
  dwave: dwave/orb-examples@2

workflows:
  version: 2.1
  tests:
    jobs:
      - dwave/test-linux:
          dwave-log-level: "debug" # Print debug msgs to avoid timeouts (likely a short term fix)
      - dwave/test-osx:
          dwave-log-level: "debug"
      - dwave/test-win:
          dwave-log-level: "debug"

  weekly:
    triggers:
      - schedule:
          cron: "0 15 * * 2"
          filters:
            branches:
              only:
                - master
                - main
    jobs:
      - dwave/test-linux:
          dwave-log-level: "debug"
      - dwave/test-osx:
          dwave-log-level: "debug"
      - dwave/test-win:
          dwave-log-level: "debug"
